name: thread
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0-177.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  objectbox: ^1.7.2
  path_provider: ^2.0.12
  objectbox_flutter_libs: any

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  build_runner: ^2.0.0
  objectbox_generator: any
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

